added router links
I have added router link. please take care of the changes in html files as per the error below
core.mjs:24932 Angular is running in development mode. Call enableProdMode() to enable production mode.
index.js:551 [webpack-dev-server] Live Reloading enabled.
index.js:561 [webpack-dev-server] Errors while compiling. Reload prevented.
logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:233
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50
2index.js:561 [webpack-dev-server] ERROR
src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.html:6:67 - error TS2339: Property 'placeName' does not exist on type 'Storeoffersadd'.

6            #cardOwnerName="ngModel" [(ngModel)]="service.formData.placeName">
                                                                    ~~~~~~~~~

  src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.ts:10:16
    10   templateUrl: './storeoffersaddform.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StoreoffersaddformComponent.

logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:246
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50
2index.js:561 [webpack-dev-server] ERROR
src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.html:11:64 - error TS2339: Property 'description' does not exist on type 'Storeoffersadd'.

11            #cardNumber="ngModel" [(ngModel)]="service.formData.description">
                                                                  ~~~~~~~~~~~

  src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.ts:10:16
    10   templateUrl: './storeoffersaddform.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StoreoffersaddformComponent.

logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:246
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50
2index.js:561 [webpack-dev-server] ERROR
src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.html:17:66 - error TS2339: Property 'category' does not exist on type 'Storeoffersadd'.

17              #cardNumber="ngModel" [(ngModel)]="service.formData.category">
                                                                    ~~~~~~~~

  src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.ts:10:16
    10   templateUrl: './storeoffersaddform.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StoreoffersaddformComponent.

logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:246
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50
2index.js:561 [webpack-dev-server] ERROR
src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.html:22:66 - error TS2339: Property 'distance' does not exist on type 'Storeoffersadd'.

22              #cardNumber="ngModel" [(ngModel)]="service.formData.distance">
                                                                    ~~~~~~~~

  src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.ts:10:16
    10   templateUrl: './storeoffersaddform.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StoreoffersaddformComponent.

logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:246
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50
index.js:561 [webpack-dev-server] ERROR
src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.html:34:123 - error TS2339: Property 'isNewOfferPosted' does not exist on type 'StoreoffersaddformComponent'.

34   <div style="border: solid; border-color: forestgreen; fill: chartreuse;border-radius:8px;vertical-align:central" *ngIf="isNewOfferPosted">
                                                                                                                             ~~~~~~~~~~~~~~~~

  src/app/storeoffersadd/storeoffersaddform/storeoffersaddform.component.ts:10:16
    10   templateUrl: './storeoffersaddform.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component StoreoffersaddformComponent.

logger @ index.js:561
(anonymous) @ index.js:731
error @ index.js:180
errors @ index.js:246
(anonymous) @ socket.js:57
client.onmessage @ WebSocketClient.js:50